### ISSUE TITLE
React SDK and rxjs version problem

### ISSUE THREAD

**Issue by Amenocy** [mean-expert-official/loopback-sdk-builder#632]
#### What type of issue are you creating?
- [* ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

in react SDK output code is like this : 
```
 return from(request)
        .map((res) => res.data)
        .catch((e) => errorHandler.handleError(e));
```
and it is not working with rxjs 5.6 and 6.3
`Uncaught TypeError: (0 , _rxjs.from)(...).map is not a function`
but in angular code it uses pipes .

**Comment by Amenocy** [comment]
problem for base services fixed in this commit : 
https://github.com/InovaMind/loopback-sdk-builder/commit/0eb195b84abb2eabc40088ecc07c66a5e8427877

but problem already exist for custom model services (lib/templates/shared/services/custom/service.ejs).
please merge that and fix for custom models.
