### ISSUE TITLE
Cannot find module 'socket.connections'.

### ISSUE THREAD

**Issue by dooddy** [mean-expert-official/loopback-sdk-builder#111]
After update to 2.0.7 in base.service the line is appeared

```typescript
import { SocketConnections } from '../../sockets/socket.connections';
```

`SocketConnections` is not used here and it causes the error below

```
scripts/shared/sdk/services/core/base.service.ts(12,35): error TS2307: Cannot find module '../../sockets/socket.connections'.
```

**Comment by jonathan-casarrubias** [comment]
Enjoy!!!
