### ISSUE TITLE
What version of rxjs should I use in my Angular 4 client

### ISSUE THREAD

**Issue by redaikidoka** [mean-expert-official/loopback-sdk-builder#630]
#### What type of issue are you creating?
- [x  ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [x ] 2.3.1

Write other if any:

#### Please add a description for your issue:

I'm upgrading from an old version of the builder     "@mean-expert/loopback-sdk-builder": "2.1.0-rc.9",
to 2.3.1 (the current version)

In my angular 4 client, I've been using rxjs 5.4.3, but I get errors like: 
datasdk/services/core/error.service.ts (4,22): Module '"/node_modules/rxjs/Rx"' has no exported member 'throwError'

I've tried the latest rxjs releases from 6 up, but can't seem to find one that builds.

Any suggestions? Is this in the docs somewhere and I missed it?

**Comment by Nosfistis** [comment]
You should use RxJS 6+ and change your usage to that.

**Comment by Amenocy** [comment]
when compile with webpack , rxjs 6.3
```
TypeError: (0 , _rxjs.from)(...).map is not a function
    at MemberApi.request (base.service.js:146)

```
for this code : 
```
 return from(request)
        .map((res) => res.data)
        .catch((e) => errorHandler.handleError(e));
```

i have this line but it seems not working 
`import { mergeMap, delay, map, catchError } from 'rxjs/operators';
`
